USE [ETRADE4]
GO

/****** Object:  View [dbo].[TariheGöreSiparisDagilimi]    Script Date: 9.10.2023 22:48:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[TariheGöreSiparisDagilimi]

AS

SELECT TOP 10000000

DATEPART(YEAR,O.DATE_) SÝPARÝÞ_YILI, 
DATEPART(MONTH,O.DATE_) SÝPARÝÞ_AYI,
CASE 
	WHEN DATEPART(MONTH,O.DATE_)=1 THEN 'OCAK'
	WHEN DATEPART(MONTH,O.DATE_)=2 THEN 'ÞUBAT'
	WHEN DATEPART(MONTH,O.DATE_)=3 THEN 'MART'
	WHEN DATEPART(MONTH,O.DATE_)=4 THEN 'NÝSAN'
	WHEN DATEPART(MONTH,O.DATE_)=5 THEN 'MAYIS'
	WHEN DATEPART(MONTH,O.DATE_)=6 THEN 'HAZÝRAN'
	WHEN DATEPART(MONTH,O.DATE_)=7 THEN 'TEMMUZ'
	WHEN DATEPART(MONTH,O.DATE_)=8 THEN 'AÐUSTOS'
	WHEN DATEPART(MONTH,O.DATE_)=9 THEN 'EYLÜL'
	WHEN DATEPART(MONTH,O.DATE_)=10 THEN 'EKÝM'
	WHEN DATEPART(MONTH,O.DATE_)=11 THEN 'KASIM'
	WHEN DATEPART(MONTH,O.DATE_)=12 THEN 'ARALIK'
END AY_ADI,

COUNT(OD.ID) SÝPARÝÞ_SAYISI, SUM(OD.AMOUNT) SÝPARÝÞ_ADEDÝ, SUM(OD.LINETOTAL) TOPLAM_SÝPARÝÞ_TUTARI,
SUM(OD.LINETOTAL)/SUM(OD.AMOUNT) ORTALAMA_BÝRÝM_FÝYAT
FROM ORDERS O


INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
INNER JOIN ITEMS I ON I.ID=OD.ITEMID

GROUP BY DATEPART(YEAR,O.DATE_), DATEPART(MONTH,O.DATE_)

ORDER BY DATEPART(YEAR,O.DATE_), DATEPART(MONTH,O.DATE_)
GO


